### ISSUE TITLE
Impossible to make it working; 503 error about websocket connection

### ISSUE THREAD

**Issue by sneko** [mchmarny/knative-ws-example#2]
Hi @mchmarny ,

Thank you for providing this example. Unfortunately I'm unable to make it working, I can reach the UI onto my domain, but it displays "Connection closed" directly, and when looking at the browser console I always see this error:
```
WebSocket connection to 'ws://demo.XXXXXXX.net/ws' failed: Error during WebSocket handshake: Unexpected response code: 503
```

My cluster is running with Cloud Run on GKE and if you did the same I would appreciate if you could share how you created the cluster 😃 

I will explain below what I did to test different situations :

## Attempt 0

On my regular cluster already customized I deployed my own websocket application, but when using a WS client, I get the 503 error mentioned above.

Note that when using `kubectl port-forward ...` onto the pod directly, I'm able to connect to the WS server. It seemed to me something was wrong at another layer (Knative/Istio ?).

After some research I saw Ahmet message pointing to your sample https://github.com/ahmetb/cloud-run-faq/issues/33#issuecomment-508969801 following a question about websockets on Cloud Run with GKE.

## Attempt 1 

Trying your sample on my existing cluster, it doesn't work, still 503.

SInce my cluster could have a misconfiguration I decide to make it from a new one.

## Attempt 2

Taking all settings I was using before but without some patchs to hack some things about SSL with Cloud Run, I end using:
```
gcloud beta container clusters create demo-deux-cluster \
  --addons=HorizontalPodAutoscaling,HttpLoadBalancing,Istio,CloudRun \
  --machine-type=n1-standard-4 \
  --num-nodes=1 \
  --cluster-version=latest \
  --region=europe-west1-b \
  --enable-stackdriver-kubernetes \
  --enable-ip-alias \
  --scopes cloud-platform
```

Still 503 error.

## Attempt 3

I decide to get rid of all extra stuff:
```
gcloud beta container clusters create demo-trois-cluster \
  --addons=HttpLoadBalancing,CloudRun \
  --machine-type=n1-standard-4 \
  --num-nodes=1 \
  --cluster-version=latest \
  --region=europe-west1-b \
  --enable-stackdriver-kubernetes
```

Still 503 error.

## Attempt 4

I'm adding a new time the Istio addon, in case, while changing the region/zone to US (thinking something could be wrong with Cloud Run Europe...):
```
gcloud beta container clusters create demo-quatre-cluster \
  --addons=HttpLoadBalancing,Istio,CloudRun \
  --machine-type=n1-standard-4 \
  --num-nodes=1 \
  --cluster-version=latest \
  --region=us-central1-a \
  --enable-stackdriver-kubernetes
```

Still 503 error.

## Attempt 5

Since the repo is no longer recent (more than a year), I decide to try different versions of GKE:
```
gcloud container clusters create demo-cinq-cluster \
  --addons=HttpLoadBalancing,CloudRun \
  --machine-type=n1-standard-4 \
  --num-nodes=1 \
  --cluster-version=1.15.11-gke.3 \
  --zone=us-central1-a \
  --enable-stackdriver-kubernetes
```

Still 503 error.

## Attempt 6

Same here, tried an older version. I wanted to use a GKE version from early 2019 but the GCloud CLI prevents me to install them (`gcloud` and `gcloud beta`) so that's the older one I was able to use:
```
gcloud beta container clusters create demo-six-cluster \
  --addons=HttpLoadBalancing,Istio,CloudRun \
  --machine-type=n1-standard-4 \
  --num-nodes=1 \
  --cluster-version=1.14.10-gke.27 \
  --zone=us-central1-a \
  --enable-stackdriver-kubernetes
```

Still 503 error.

## Conclusion

I'm lost 😄. I really hope that's a mistake on my own and that someone could help me.

Starting from scratch with new clusters, different minimal settings, different regions... and not being able to reproduce your sample makes me wondering what am I doing wrong.

Maybe the simple answer is this repo was tested on a Knative cluster without Cloud Run? But Ahmet seems to say it would work also since it's based on Knative/Istio.

🤞 

Thank you,

**Comment by sneko** [comment]
Hi @mchmarny , I'm still stuck with this issue... it's broader than just with your sample, even my own GraphQL API is not working and get the same issue.

I'm just wondering if you set additional settings to your "Google Cloud Run on GKE" cluster or to your Istio settings so the sample was able to work properly?

Note: as mentioned above, when doing direct `kubectl port-forward` onto the cluster, I'm able make it working (and no longer have 503 error for websockets), both with my own API and also your sample.

Thank you,

**Comment by mchmarny** [comment]
This is pretty old. I will take a look but I now and I no longer work on Kantive so wonder if it may be faster to start with the official Knative sample which is maintain by the Knative team: https://github.com/knative-sample/websocket-chat

All best,

**Comment by sneko** [comment]
Hi @mchmarny ,

Thank you for pointing to another example! After some testing with Knative team, it seems my issue **could come** from the "service DomainMapping" feature in Cloud Run (https://github.com/knative/serving/issues/7933#issuecomment-632924229).

When bypassing DomainMapping, I can make your last link working, and also your sample without any issue.

Thank you for answering me!
